# Generated by Django 6.0.6 on 2026-07-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='foto',
            field=models.URLField(),
        ),
    ]
